In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Docbot_Dataset.csv')
data.head(5)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0     Alam                                0                 1   
1    Kadir                                1                 0   
2    Farid                                1                 0   
3    Rahim                                0                 0   
4   Barsha                                0                 0   

   Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                  0                  0        0                        0   
1                  0                  0        0                        0   
2                  0                  0        0                        0   
3                  0                  1        0                        0   
4                  0                  0        1                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                          0              0                           1  ...   
1                          1              1                           0  ...   
2                          1              0                           1  ...   
3                          0              0                           1  ...   
4                          0              0                           1  ...   

   Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0          1       0                     0                     0   
1          1       1                     1                     0   
2          0       1                     0                     1   
3          1       0                     0                     0   
4          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   

   Presents of light when eye lid close  Result/Outcome  
0                                     0             101  
1                                     0             201  
2                                     0             201  
3                                     0             301  
4                                     0             401  

[5 rows x 21 columns]

In [3]:
data.shape

(563, 21)

In [4]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,1:20].values
real_y = data.iloc[:,20].values

In [5]:
real_x

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [6]:
real_y

array([101, 201, 201, 301, 401, 401, 201, 501, 301, 401, 301, 301, 301,
       301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 10

In [7]:
# Supervised learning e ... dataset -->> traing ar testing dataset e divided kora hoy
# training er data ... 70-80 % rakte hbe er theke besi ora kom hote parbe na 
# testing er data ... baki % e rakbo


from sklearn.model_selection import train_test_split  # divide korar jonno library
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.2,random_state = 0)  # data set split kortesi
            # randodm_state = 0 na dile ans ekbar ekta asbo 



In [8]:
testing_x

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0]], dtype=int64)

In [9]:
training_x

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [10]:
from sklearn.linear_model import LinearRegression  # Model built er jonno library
MLR = LinearRegression() # ei cls er object ---> Lin
MLR.fit(training_x,training_y) # ei khane ei Model train kora hoise # Model ke fit kora hoise  --> fit = cls e 2 ta argument nei ei gula Training er sate related


LinearRegression()

In [11]:
testing_y # real Value

array([501, 201, 101, 501, 201, 201, 401, 201, 201, 401, 301, 201, 101,
       101, 101, 201, 101, 201, 401, 201, 201, 201, 101, 101, 101, 201,
       101, 201, 101, 501, 201, 301, 101, 201, 401, 401, 501, 201, 401,
       101, 201, 501, 501, 201, 401, 201, 201, 201, 201, 501, 301, 201,
       201, 201, 201, 301, 201, 501, 401, 501, 201, 101, 201, 401, 101,
       501, 401, 501, 201, 101, 201, 101, 101, 501, 301, 101, 101, 101,
       501, 201, 101, 401, 201, 101, 201, 201, 201, 101, 201, 201, 301,
       301, 101, 501, 401, 201, 501, 201, 201, 201, 401, 201, 101, 101,
       201, 201, 201, 401, 201, 301, 201, 101, 101], dtype=int64)

In [12]:
Pred_y = MLR.predict(testing_x)
Pred_y  # prediction Value

array([406.60215394, 188.37033784, 194.18747349, 409.05525436,
       183.47787892, 175.56645382, 291.89637032, 201.10967378,
       238.71004522, 349.47970811, 294.44581394, 187.65399252,
       171.19993073, 109.45168786,  95.98479808, 212.51168845,
       104.55922893, 227.12509101, 468.001891  , 227.84143634,
       179.74256742, 227.58780612,  84.5827834 , 184.95586871,
       125.20212102, 233.8175863 , 164.97015055, 183.47787892,
       102.21457826, 475.38896008, 199.77235252, 338.45746642,
        84.5827834 , 228.27333014, 469.1044543 , 322.77934073,
       482.33333231, 182.32963979, 411.9017616 , 144.33653108,
       234.35099209, 439.50152519, 270.23569478, 256.87524587,
       423.30377628, 183.47787892, 190.24106489, 239.24345101,
       190.24106489, 304.44805342, 300.29752433, 244.75688587,
       183.47787892, 188.37033784, 239.99082437, 276.2587505 ,
       194.8798936 , 205.58948817, 343.24992793, 546.54808464,
       224.09721654, 145.17856656, 183.47787892, 329.55

In [13]:
# eita formula diya korar way but ota ektu kotin tai eta ektu dekai se # aage simple eay te kora ase

MLR.coef_   # Multiple input tai multiple asce  # Coeficient er value

array([-46.7925757 , -59.75374768, -40.61933762,  15.63568831,
        53.03778762, 143.0596047 ,  -6.76318597,  -4.1761136 ,
        -4.89245892, -11.40201468, -17.63179486, -68.98535247,
        27.98257846,   7.9114251 ,  14.97784295,  79.13758975,
        53.95404623, -19.97644553, 124.67835431])

In [14]:
MLR.intercept_   # Intercept er value # Output ektai

307.8439351649781

In [15]:
print('Train Score: ', MLR.score(training_x,training_y))  
print('Test Score: ', MLR.score(testing_x, testing_y))  

Train Score:  0.8682669776265864
Test Score:  0.7690656255485897


In [16]:
import statistics
ac = statistics.mean(testing_y*Pred_y)
ac/1000

74.28239971251594

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
confus_matrix = confusion_matrix(testing_y,Pred_y )  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets