In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Docbot_Dataset.csv')
data.head(5)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0     Alam                                0                 1   
1    Kadir                                1                 0   
2    Farid                                1                 0   
3    Rahim                                0                 0   
4   Barsha                                0                 0   

   Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                  0                  0        0                        0   
1                  0                  0        0                        0   
2                  0                  0        0                        0   
3                  0                  1        0                        0   
4                  0                  0        1                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                          0              0                           1  ...   
1                          1              1                           0  ...   
2                          1              0                           1  ...   
3                          0              0                           1  ...   
4                          0              0                           1  ...   

   Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0          1       0                     0                     0   
1          1       1                     1                     0   
2          0       1                     0                     1   
3          1       0                     0                     0   
4          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   

   Presents of light when eye lid close  Result/Outcome  
0                                     0             101  
1                                     0             201  
2                                     0             201  
3                                     0             301  
4                                     0             401  

[5 rows x 21 columns]

In [3]:
data.shape

(563, 21)

In [4]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,1:20].values
real_y = data.iloc[:,20].values

In [5]:
real_x

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [6]:
real_y

array([101, 201, 201, 301, 401, 401, 201, 501, 301, 401, 301, 301, 301,
       301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 10

In [7]:
# Supervised learning e ... dataset -->> traing ar testing dataset e divided kora hoy
# training er data ... 70-80 % rakte hbe er theke besi ora kom hote parbe na 
# testing er data ... baki % e rakbo


from sklearn.model_selection import train_test_split  # divide korar jonno library
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.2,random_state = 0)  # data set split kortesi
            # randodm_state = 0 na dile ans ekbar ekta asbo 



In [8]:
testing_x

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0]], dtype=int64)

In [9]:
training_x

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [10]:
from sklearn.linear_model import LinearRegression  # Model built er jonno library
MLR = LinearRegression() # ei cls er object ---> Lin
MLR.fit(training_x,training_y) # ei khane ei Model train kora hoise # Model ke fit kora hoise  --> fit = cls e 2 ta argument nei ei gula Training er sate related


LinearRegression()

In [11]:
testing_y # real 

array([501, 201, 101, 501, 201, 201, 401, 201, 201, 401, 301, 201, 101,
       101, 101, 201, 101, 201, 401, 201, 201, 201, 101, 101, 101, 201,
       101, 201, 101, 501, 201, 301, 101, 201, 401, 401, 501, 201, 401,
       101, 201, 501, 501, 201, 401, 201, 201, 201, 201, 501, 301, 201,
       201, 201, 201, 301, 201, 501, 401, 501, 201, 101, 201, 401, 101,
       501, 401, 501, 201, 101, 201, 101, 101, 501, 301, 101, 101, 101,
       501, 201, 101, 401, 201, 101, 201, 201, 201, 101, 201, 201, 301,
       301, 101, 501, 401, 201, 501, 201, 201, 201, 401, 201, 101, 101,
       201, 201, 201, 401, 201, 301, 201, 101, 101], dtype=int64)

In [12]:
Pred_y = MLR.predict(testing_x)
Pred_y  # prediction

array([406.60215394, 188.37033784, 194.18747349, 409.05525436,
       183.47787892, 175.56645382, 291.89637032, 201.10967378,
       238.71004522, 349.47970811, 294.44581394, 187.65399252,
       171.19993073, 109.45168786,  95.98479808, 212.51168845,
       104.55922893, 227.12509101, 468.001891  , 227.84143634,
       179.74256742, 227.58780612,  84.5827834 , 184.95586871,
       125.20212102, 233.8175863 , 164.97015055, 183.47787892,
       102.21457826, 475.38896008, 199.77235252, 338.45746642,
        84.5827834 , 228.27333014, 469.1044543 , 322.77934073,
       482.33333231, 182.32963979, 411.9017616 , 144.33653108,
       234.35099209, 439.50152519, 270.23569478, 256.87524587,
       423.30377628, 183.47787892, 190.24106489, 239.24345101,
       190.24106489, 304.44805342, 300.29752433, 244.75688587,
       183.47787892, 188.37033784, 239.99082437, 276.2587505 ,
       194.8798936 , 205.58948817, 343.24992793, 546.54808464,
       224.09721654, 145.17856656, 183.47787892, 329.55

# wrong But for test

Final_Accurcy_test = (Pred_y / testing_y)*100
Final_Accurcy_test

In [13]:
# eita formula diya korar way but ota ektu kotin tai eta ektu dekai se # aage simple eay te kora ase

MLR.coef_   # Multiple input tai multiple asce  # Coeficient er value

array([-46.7925757 , -59.75374768, -40.61933762,  15.63568831,
        53.03778762, 143.0596047 ,  -6.76318597,  -4.1761136 ,
        -4.89245892, -11.40201468, -17.63179486, -68.98535247,
        27.98257846,   7.9114251 ,  14.97784295,  79.13758975,
        53.95404623, -19.97644553, 124.67835431])

In [14]:
MLR.intercept_   # Intercept er value # Output ektai

307.8439351649781

In [15]:
import statsmodels.formula.api as sm # need for backword elimination remove korbar jonno

In [16]:
real_x = np.append(arr=np.ones((563,1)).astype(int),values=real_x,axis=1)  # x0 = 1 kora hoise  # Shift + tab --> dekbo
real_x

array([[1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [17]:
X_opt = np.array(real_x[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]], dtype=float)  # dtype=float ---> eta na dile pore kaje vul asbe
X_opt

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 1., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [18]:
import statsmodels.api as sm

regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()

                # fit() -- Model Train Korsi
                # OLS = Ordinary List Square Method
                # endog = Output Value
                # exog = Input Value oR Optimize Value 

In [19]:
regressor_OLS.summary()   # Sob gular Summary aisa gase

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.850
Model:                            OLS   Adj. R-squared:                  0.844
Method:                 Least Squares   F-statistic:                     161.5
Date:                Mon, 05 Oct 2020   Prob (F-statistic):          4.72e-209
Time:                        12:49:39   Log-Likelihood:                -2994.8
No. Observations:                 563   AIC:                             6030.
Df Residuals:                     543   BIC:                             6116.
Df Model:                          19                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        320.1225      9.847     32.510      0.000     300.780     339.465
x1           -54.7240      9.078     -6.028      0.000     -72.555     -36.893
x2           -64.9896      7.742     -8.395      0.000     -80.197     -49.782
x3           -41.2093      5.779     -7.131      0.000     -52.561     -29.858
x4             9.6418     12.504      0.771      0.441     -14.920      34.204
x5            52.8865     10.414      5.078      0.000      32.430      73.343
x6           134.9551     11.085     12.175      0.000     113.181     156.729
x7           -12.9495      7.720     -1.677      0.094     -28.114       2.215
x8            -6.8479      7.467     -0.917      0.360     -21.516       7.820
x9            -8.5613      5.146     -1.664      0.097     -18.669       1.547
x10          -12.7859      5.110     -2.502      0.013     -22.824      -2.747
x11          -12.9603      5.089     -2.547      0.011     -22.958      -2.963
x12          -80.8049      7.508    -10.763      0.000     -95.553     -66.057
x13           30.0920     14.647      2.054      0.040       1.320      58.864
x14           12.5677      7.441      1.689      0.092      -2.049      27.184
x15            4.6527     12.301      0.378      0.705     -19.511      28.816
x16           59.4608     10.088      5.894      0.000      39.644      79.277
x17           53.8235      9.959      5.405      0.000      34.261      73.386
x18          -14.1199      7.176     -1.968      0.050     -28.216      -0.023
x19          118.0599     11.008     10.725      0.000      96.437     139.683
==============================================================================
Omnibus:                      146.851   Durbin-Watson:                   0.972
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              911.189
Skew:                           0.991   Prob(JB):                    1.37e-198
Kurtosis:                       8.909   Cond. No.                         15.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
X_opt = np.array(real_x[:, [0, 1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,16,17,18,19]], dtype=float) # 15 remove bcoz SL=0.5
regressor_OLS = sm.OLS(endog = real_y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.850
Model:                            OLS   Adj. R-squared:                  0.845
Method:                 Least Squares   F-statistic:                     170.7
Date:                Mon, 05 Oct 2020   Prob (F-statistic):          3.83e-210
Time:                        12:49:40   Log-Likelihood:                -2994.9
No. Observations:                 563   AIC:                             6028.
Df Residuals:                     544   BIC:                             6110.
Df Model:                          18                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        321.3484      9.291     34.587      0.000     303.098     339.599
x1           -55.3539      8.916     -6.208      0.000     -72.869     -37.839
x2           -65.1290      7.727     -8.429      0.000     -80.307     -49.951
x3           -41.4445      5.741     -7.219      0.000     -52.721     -30.168
x4            11.2257     11.773      0.954      0.341     -11.899      34.351
x5            52.5631     10.371      5.068      0.000      32.192      72.935
x6           134.4207     10.986     12.236      0.000     112.841     156.000
x7           -13.2114      7.683     -1.720      0.086     -28.303       1.880
x8            -7.0871      7.434     -0.953      0.341     -21.691       7.516
x9            -8.6138      5.140     -1.676      0.094     -18.710       1.482
x10          -12.7742      5.106     -2.502      0.013     -22.804      -2.744
x11          -13.0490      5.080     -2.569      0.010     -23.028      -3.070
x12          -81.2021      7.428    -10.931      0.000     -95.794     -66.610
x13           30.3319     14.622      2.074      0.039       1.609      59.055
x14           12.6903      7.428      1.708      0.088      -1.901      27.282
x15           58.8923      9.968      5.908      0.000      39.313      78.472
x16           53.3135      9.860      5.407      0.000      33.946      72.681
x17          -14.5662      7.073     -2.059      0.040     -28.460      -0.673
x18          117.5309     10.910     10.773      0.000      96.100     138.962
==============================================================================
Omnibus:                      145.071   Durbin-Watson:                   0.979
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              897.478
Skew:                           0.977   Prob(JB):                    1.30e-195
Kurtosis:                       8.868   Cond. No.                         15.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# tar 15 no Column bad diiya abr M.L.R Apply korle valo prediction pabo

# ekhon jei gula paisi ei gulai Optimize result (x1 - x19) , P>|t| = 0.000 ,Here SL = 0.5 (Consider)

* ei Algorithm use hoy Most Significant Indipendent variable ke Find out korar jonno

In [21]:
#print('Train Score: ', regressor.score(x_train, y_train))  
#print('Test Score: ', regressor.score(x_test, y_test))  