Reference: https://machinelearningmastery.com/develop-first-xgboost-model-python-scikit-learn/

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('DatasetDocBot_final.csv')
data.head(5)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0     Alam                                0                 1   
1    Kadir                                1                 0   
2    Farid                                1                 0   
3    Rahim                                0                 0   
4   Barsha                                0                 0   

   Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                  0                  0        0                        0   
1                  0                  0        0                        0   
2                  0                  0        0                        0   
3                  0                  1        0                        0   
4                  0                  0        1                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                          0              0                           1  ...   
1                          1              1                           0  ...   
2                          1              0                           1  ...   
3                          0              0                           1  ...   
4                          0              0                           1  ...   

   Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0          1       0                     0                     0   
1          1       1                     1                     0   
2          0       1                     0                     1   
3          1       0                     0                     0   
4          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   

   Presents of light when eye lid close       Result/Outcome  
0                                     0  Oculer hypertension  
1                                     0             Catracts  
2                                     0             Catracts  
3                                     0         Bulgy Vision  
4                                     0         Glaucoma ACG  

[5 rows x 21 columns]

In [3]:
real_x = data.iloc[:,1:20].values
real_y = data.iloc[:,20].values

In [4]:
real_x

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [5]:
real_y

array(['Oculer hypertension', 'Catracts', 'Catracts', 'Bulgy Vision',
       'Glaucoma ACG', 'Glaucoma ACG', 'Catracts', 'Congenital Glaucoma',
       'Bulgy Vision', 'Glaucoma ACG', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertensio

In [6]:
from sklearn.model_selection import train_test_split # aage eta use hotw-->from sklearn.cross_validation import train_test_split
training_x,test_x,training_y,test_y = train_test_split(real_x,real_y,test_size = 0.25, random_state=0)

In [7]:
training_x

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [8]:
test_x

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

# XGBoost Model

# xgboost --- > Anaconda theke bha pip diya install kora lage

In [9]:
from xgboost import XGBClassifier
# fit model no training data
model = XGBClassifier()
model.fit(training_x, training_y)

XGBClassifier(objective='multi:softprob')

In [10]:
print(model)

XGBClassifier(objective='multi:softprob')


In [11]:
model.score(test_x, test_y)

0.950354609929078

In [12]:
y_pred = model.predict(test_x)
y_pred  # prediction

array(['Congenital Glaucoma', 'Catracts', 'Oculer hypertension',
       'Congenital Glaucoma', 'Catracts', 'Catracts', 'Glaucoma ACG',
       'Catracts', 'Catracts', 'Glaucoma ACG', ' Bulgy Vision',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Congenital Glaucoma',
       'Catracts', ' Bulgy Vision', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Glaucoma ACG', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Oculer hypertension', 'Catracts',
       'Congenital Glaucoma', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Congenital Glaucoma', ' Bulgy Vision', 'Catracts', 'Catracts',
       

In [13]:
test_y  # Real

array(['Congenital Glaucoma', 'Catracts', 'Oculer hypertension',
       'Congenital Glaucoma', 'Catracts', 'Catracts', 'Glaucoma ACG',
       'Catracts', 'Catracts', 'Glaucoma ACG', ' Bulgy Vision',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Congenital Glaucoma',
       'Catracts', 'Bulgy Vision', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Glaucoma ACG', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Oculer hypertension', 'Catracts',
       'Congenital Glaucoma', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Congenital Glaucoma', 'Bulgy Vision', 'Catracts', 'Catracts',
       'C

# confus_matrix

In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
confus_matrix = confusion_matrix(test_y,y_pred)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[ 3,  1,  0,  0,  0,  0],
       [ 4,  1,  0,  0,  0,  0],
       [ 0,  0, 63,  1,  0,  0],
       [ 0,  0,  0, 15,  0,  1],
       [ 0,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0, 37]], dtype=int64)

# Accuracy

In [16]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(test_y, y_pred))

Accuracy :  0.950354609929078


In [17]:
print (accuracy_score(test_y, y_pred)*100) # Accuracy

95.0354609929078


# precision, recall, f1-score, support

In [18]:
from sklearn.metrics import classification_report
print(classification_report(test_y, y_pred))

                     precision    recall  f1-score   support

       Bulgy Vision       0.43      0.75      0.55         4
       Bulgy Vision       0.50      0.20      0.29         5
           Catracts       1.00      0.98      0.99        64
Congenital Glaucoma       0.94      0.94      0.94        16
       Glaucoma ACG       1.00      1.00      1.00        15
Oculer hypertension       0.97      1.00      0.99        37

           accuracy                           0.95       141
          macro avg       0.81      0.81      0.79       141
       weighted avg       0.95      0.95      0.95       141

