In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Docbot_Dataset_Random Forest.csv')
data.head(5)

Clouldy, blurry or foggy vision  Pressure in Eye?  Injury to the Eye  \
0                                0                 1                  0   
1                                1                 0                  0   
2                                1                 0                  0   
3                                0                 0                  0   
4                                0                 0                  0   

   Excessive dryness  Red eye  Cornea increase in size  \
0                  0        0                        0   
1                  0        0                        0   
2                  0        0                        0   
3                  1        0                        0   
4                  0        1                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  \
0                          0              0                           1   
1                          1              1                           0   
2                          1              0                           1   
3                          0              0                           1   
4                          0              0                           1   

   40+ age  Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0        1          1       0                     0                     0   
1        1          1       1                     1                     0   
2        0          0       1                     0                     1   
3        1          1       0                     0                     0   
4        1          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   

   Presents of light when eye lid close  Result/Outcome  
0                                     0             101  
1                                     0             201  
2                                     0             201  
3                                     0             301  
4                                     0             401

In [3]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,1:19].values
real_y = data.iloc[:,19].values

In [4]:
real_x

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [5]:
real_y

array([101, 201, 201, 301, 401, 401, 201, 501, 301, 401, 301, 301, 301,
       301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 301, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101,
       101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 10

In [6]:
# Supervised learning e ... dataset -->> traing ar testing dataset e divided kora hoy
# training er data ... 70-80 % rakte hbe er theke besi ora kom hote parbe na 
# testing er data ... baki % e rakbo


from sklearn.model_selection import train_test_split  # divide korar jonno library
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.2,random_state = 0)  # data set split kortesi
            # randodm_state = 0 na dile ans ekbar ekta asbo 


In [7]:
testing_x

array([[0, 0, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [8]:
training_x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [9]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor(n_estimators=100,random_state=0)
reg.fit(real_x,real_y)

RandomForestRegressor(random_state=0)

In [10]:
testing_y # real Value

array([501, 201, 101, 501, 201, 201, 401, 201, 201, 401, 301, 201, 101,
       101, 101, 201, 101, 201, 401, 201, 201, 201, 101, 101, 101, 201,
       101, 201, 101, 501, 201, 301, 101, 201, 401, 401, 501, 201, 401,
       101, 201, 501, 501, 201, 401, 201, 201, 201, 201, 501, 301, 201,
       201, 201, 201, 301, 201, 501, 401, 501, 201, 101, 201, 401, 101,
       501, 401, 501, 201, 101, 201, 101, 101, 501, 301, 101, 101, 101,
       501, 201, 101, 401, 201, 101, 201, 201, 201, 101, 201, 201, 301,
       301, 101, 501, 401, 201, 501, 201, 201, 201, 401, 201, 101, 101,
       201, 201, 201, 401, 201, 301, 201, 101, 101], dtype=int64)

In [11]:
Pred_y = reg.predict(testing_x)
Pred_y 

array([498., 201., 157., 501., 201., 201., 351., 201., 201., 398., 301.,
       201., 101., 101., 101., 201., 101., 201., 401., 201., 201., 201.,
       101., 132., 101., 201., 101., 201., 101., 498., 201., 301., 101.,
       201., 414., 389., 501., 202., 401., 101., 201., 501., 484., 201.,
       401., 201., 201., 201., 201., 454., 301., 203., 201., 201., 201.,
       270., 201., 382., 401., 501., 201., 107., 201., 383., 101., 501.,
       401., 501., 201., 106., 201., 101., 101., 501., 298., 101., 101.,
       101., 501., 201., 101., 401., 201., 101., 285., 201., 201., 101.,
       201., 201., 301., 301., 101., 388., 399., 201., 501., 201., 201.,
       201., 383., 201., 101., 105., 201., 201., 207., 401., 201., 334.,
       201., 101., 101.])

In [12]:

y_predict = reg.predict([[1,0,0,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0]])
y_predict

array([295.])

In [13]:
reg = RandomForestRegressor(n_estimators=50,random_state=0)
reg.fit(real_x,real_y)

y_predict = reg.predict([[1,0,0,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0]])
y_predict   # n_estimator = joto besi hbe toto Reslt valo hbe

array([281.])

# confus_matrix

In [14]:
from sklearn.metrics import confusion_matrix

In [16]:
confus_matrix = confusion_matrix(testing_y,Pred_y)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[23,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 44,  1,  1,  1,  0,  1,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  

# Accuracy 

In [17]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(testing_y,Pred_y))

Accuracy :  0.7787610619469026


In [18]:
print (accuracy_score(testing_y,Pred_y)*100) # Accuracy

77.87610619469027


# precision, recall, f1-score, support

In [19]:
from sklearn.metrics import classification_report
print(classification_report(testing_y,Pred_y))

              precision    recall  f1-score   support

       101.0       1.00      0.82      0.90        28
       105.0       0.00      0.00      0.00         0
       106.0       0.00      0.00      0.00         0
       107.0       0.00      0.00      0.00         0
       132.0       0.00      0.00      0.00         0
       157.0       0.00      0.00      0.00         0
       201.0       1.00      0.92      0.96        48
       202.0       0.00      0.00      0.00         0
       203.0       0.00      0.00      0.00         0
       207.0       0.00      0.00      0.00         0
       270.0       0.00      0.00      0.00         0
       285.0       0.00      0.00      0.00         0
       298.0       0.00      0.00      0.00         0
       301.0       1.00      0.62      0.77         8
       334.0       0.00      0.00      0.00         0
       351.0       0.00      0.00      0.00         0
       382.0       0.00      0.00      0.00         0
       383.0       0.00    

C:\Users\Nayeem\.conda\envs\tensorflow 3_7\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
