In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('DatasetDocBot_final.csv')
data.head(10)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0       Alam                                0                 1   
1      Kadir                                1                 0   
2      Farid                                1                 0   
3      Rahim                                0                 0   
4     Barsha                                0                 0   
5      Rifah                                0                 0   
6    Mashrar                                1                 0   
7  Oporajita                                0                 0   
8     Saliha                                0                 0   
9        eva                                0                 0   

   Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                  0                  0        0                        0   
1                  0                  0        0                        0   
2                  0                  0        0                        0   
3                  0                  1        0                        0   
4                  0                  0        1                        0   
5                  0                  0        1                        0   
6                  0                  0        0                        0   
7                  0                  0        0                        1   
8                  0                  1        0                        0   
9                  0                  0        0                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                          0              0                           1  ...   
1                          1              1                           0  ...   
2                          1              0                           1  ...   
3                          0              0                           1  ...   
4                          0              0                           1  ...   
5                          0              0                           0  ...   
6                          0              0                           1  ...   
7                          0              0                           1  ...   
8                          0              0                           0  ...   
9                          1              0                           1  ...   

   Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0          1       0                     0                     0   
1          1       1                     1                     0   
2          0       1                     0                     1   
3          1       0                     0                     0   
4          0       0                     0                     0   
5          1       0                     0                     0   
6          1       1                     0                     0   
7          0       0                     1                     0   
8          1       0                     0                     0   
9          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   
5                  0          1         0                                   0   
6                  0          0         0                                   0   
7                  0          0         0                                   1   
8                  1          0         0                  

In [3]:
# ei khane data ke 2 way te devide korbo
# input multiple hbe but output sudu ekta tai hbe

real_x = data.iloc[:,1:20].values
real_y = data.iloc[:,20].values

In [4]:
real_x

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [5]:
real_y

array(['Oculer hypertension', 'Catracts', 'Catracts', 'Bulgy Vision',
       'Glaucoma ACG', 'Glaucoma ACG', 'Catracts', 'Congenital Glaucoma',
       'Bulgy Vision', 'Glaucoma ACG', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertensio

In [6]:
from sklearn.model_selection import train_test_split # aage eta use hotw-->from sklearn.cross_validation import train_test_split
training_x,test_x,training_y,test_y = train_test_split(real_x,real_y,test_size = 0.25, random_state=0)

In [7]:
training_x

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [8]:
test_x

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
from sklearn.preprocessing import StandardScaler 

In [10]:
scaler = StandardScaler()
training_x = scaler.fit_transform(training_x) # Scalling
test_x = scaler.fit_transform(test_x)         # Scalling

In [11]:
training_x  # ei kane dektesi Data -2 theke +2 er bitore 

array([[ 1.29919132, -0.65982888, -1.18803559, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [ 1.29919132, -0.65982888,  0.84172562, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [-0.76970958,  1.51554446,  0.84172562, ..., -0.28157395,
         1.41925534, -0.25094281],
       ...,
       [ 1.29919132, -0.65982888, -1.18803559, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [-0.76970958,  1.51554446, -1.18803559, ..., -0.28157395,
         1.41925534, -0.25094281],
       [-0.76970958, -0.65982888, -1.18803559, ...,  3.55146494,
        -0.70459485, -0.25094281]])

In [12]:
test_x      # ei kane dektesi Data -2 theke +2 er bitore 

array([[-0.87321246, -0.5527708 , -1.08130975, ..., -0.26111648,
         1.48477118,  3.82970843],
       [ 1.14519667, -0.5527708 ,  0.92480439, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [-0.87321246,  1.80906807, -1.08130975, ..., -0.26111648,
         1.48477118, -0.26111648],
       ...,
       [ 1.14519667, -0.5527708 , -1.08130975, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [ 1.14519667, -0.5527708 ,  0.92480439, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [ 1.14519667, -0.5527708 , -1.08130975, ..., -0.26111648,
        -0.67350445, -0.26111648]])

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
classifer = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifer.fit(training_x,training_y,)

KNeighborsClassifier()

In [15]:
y_pred = classifer.predict(test_x)
y_pred # Prediction er value

array(['Congenital Glaucoma', 'Catracts', 'Oculer hypertension',
       'Congenital Glaucoma', 'Catracts', 'Catracts', 'Glaucoma ACG',
       'Catracts', 'Catracts', 'Glaucoma ACG', ' Bulgy Vision',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Congenital Glaucoma',
       'Catracts', ' Bulgy Vision', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Glaucoma ACG', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Oculer hypertension', 'Catracts',
       'Congenital Glaucoma', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Catracts', ' Bulgy Vision', 'Catracts', 'Catracts', 'Catracts',
      

In [16]:
test_y  # Real Data er value

array(['Congenital Glaucoma', 'Catracts', 'Oculer hypertension',
       'Congenital Glaucoma', 'Catracts', 'Catracts', 'Glaucoma ACG',
       'Catracts', 'Catracts', 'Glaucoma ACG', ' Bulgy Vision',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Congenital Glaucoma',
       'Catracts', 'Bulgy Vision', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Glaucoma ACG', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Oculer hypertension', 'Catracts',
       'Congenital Glaucoma', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Congenital Glaucoma', 'Bulgy Vision', 'Catracts', 'Catracts',
       'C

In [17]:
# test case
prediction_disease = classifer.predict([[1,0,0,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0]]) # 3 no Row # input Symptomps for prediction

In [18]:
prediction_disease # prediction

array(['Catracts'], dtype=object)

In [19]:
# Another test case
prediction_disease = classifer.predict([[0,1,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0]]) # 50 no Row # input Symptomps for prediction

In [20]:
prediction_disease # prediction

array(['Oculer hypertension'], dtype=object)

In [21]:
# Another test case
prediction_disease = classifer.predict([[0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1]]) # input Symptomps for prediction 

In [22]:
prediction_disease # prediction

array(['Oculer hypertension'], dtype=object)

# confus_matrix

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confus_matrix = confusion_matrix(test_y,y_pred)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[ 3,  1,  0,  0,  0,  0],
       [ 4,  1,  0,  0,  0,  0],
       [ 0,  0, 63,  1,  0,  0],
       [ 0,  0,  1, 13,  0,  2],
       [ 0,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0, 37]], dtype=int64)

# Accuracy

In [25]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(test_y, y_pred))

Accuracy :  0.9361702127659575


In [26]:
print (accuracy_score(test_y, y_pred)*100) # Accuracy

93.61702127659575


# precision, recall, f1-score, support

In [27]:
from sklearn.metrics import classification_report
print(classification_report(test_y, y_pred))

                     precision    recall  f1-score   support

       Bulgy Vision       0.43      0.75      0.55         4
       Bulgy Vision       0.50      0.20      0.29         5
           Catracts       0.98      0.98      0.98        64
Congenital Glaucoma       0.93      0.81      0.87        16
       Glaucoma ACG       1.00      1.00      1.00        15
Oculer hypertension       0.95      1.00      0.97        37

           accuracy                           0.94       141
          macro avg       0.80      0.79      0.78       141
       weighted avg       0.94      0.94      0.93       141

