In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('DatasetDocBot_final.csv')
data.head(5)

Patients  Clouldy, blurry or foggy vision  Pressure in Eye?  \
0     Alam                                0                 1   
1    Kadir                                1                 0   
2    Farid                                1                 0   
3    Rahim                                0                 0   
4   Barsha                                0                 0   

   Injury to the Eye  Excessive dryness  Red eye  Cornea increase in size  \
0                  0                  0        0                        0   
1                  0                  0        0                        0   
2                  0                  0        0                        0   
3                  0                  1        0                        0   
4                  0                  0        1                        0   

   Color Identifying Problem  Double Vision  Have eye problem in family  ...  \
0                          0              0                           1  ...   
1                          1              1                           0  ...   
2                          1              0                           1  ...   
3                          0              0                           1  ...   
4                          0              0                           1  ...   

   Diabetics  Myopia  Trouble with glasses  Hard to see at night  \
0          1       0                     0                     0   
1          1       1                     1                     0   
2          0       1                     0                     1   
3          1       0                     0                     0   
4          0       0                     0                     0   

   Visible Whiteness  Mass pain  Vomiting  Water drops from eyes continuously  \
0                  0          0         0                                   0   
1                  0          0         0                                   0   
2                  0          0         0                                   0   
3                  1          0         0                                   0   
4                  0          1         1                                   0   

   Presents of light when eye lid close       Result/Outcome  
0                                     0  Oculer hypertension  
1                                     0             Catracts  
2                                     0             Catracts  
3                                     0         Bulgy Vision  
4                                     0         Glaucoma ACG  

[5 rows x 21 columns]

In [3]:
real_x = data.iloc[:,1:20].values  # I/O = IV
real_y = data.iloc[:,20].values   # O/P = DV

# ekhon Data ke I/O and O/P er modde Devide korbo

In [4]:
real_x

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [5]:
real_y

array(['Oculer hypertension', 'Catracts', 'Catracts', 'Bulgy Vision',
       'Glaucoma ACG', 'Glaucoma ACG', 'Catracts', 'Congenital Glaucoma',
       'Bulgy Vision', 'Glaucoma ACG', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision', 'Bulgy Vision',
       'Bulgy Vision', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertensio

In [6]:
from sklearn.model_selection import train_test_split # aage eta use hotw-->from sklearn.cross_validation import train_test_split
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.25, random_state=0)

# I/O or O/P e Data ke Split korbo

In [7]:
training_x

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [8]:
testing_x

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

# ---> এখন korbo Features Secale
er kaj holo Data ke ekta Range e ana... -2 theke +2 er vitor e ana(Range). Bcoz, Age er Basically 10-100 er bitor But Salary holo 10K-100k... ..Huge difference tai Scalling kore hoy...Then Data Ploat korbar Jonno Valid paramrter pabo

In [9]:
from sklearn.preprocessing import StandardScaler 

In [10]:
s_c = StandardScaler()
training_x = s_c.fit_transform(training_x) # Scalling
test_x = s_c.fit_transform(testing_x)         # Scalling

In [11]:
training_x  # ei kane dektesi Data -2 theke +2 er bitore 

array([[ 1.29919132, -0.65982888, -1.18803559, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [ 1.29919132, -0.65982888,  0.84172562, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [-0.76970958,  1.51554446,  0.84172562, ..., -0.28157395,
         1.41925534, -0.25094281],
       ...,
       [ 1.29919132, -0.65982888, -1.18803559, ..., -0.28157395,
        -0.70459485, -0.25094281],
       [-0.76970958,  1.51554446, -1.18803559, ..., -0.28157395,
         1.41925534, -0.25094281],
       [-0.76970958, -0.65982888, -1.18803559, ...,  3.55146494,
        -0.70459485, -0.25094281]])

In [12]:
test_x      # ei kane dektesi Data -2 theke +2 er bitore 

array([[-0.87321246, -0.5527708 , -1.08130975, ..., -0.26111648,
         1.48477118,  3.82970843],
       [ 1.14519667, -0.5527708 ,  0.92480439, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [-0.87321246,  1.80906807, -1.08130975, ..., -0.26111648,
         1.48477118, -0.26111648],
       ...,
       [ 1.14519667, -0.5527708 , -1.08130975, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [ 1.14519667, -0.5527708 ,  0.92480439, ..., -0.26111648,
        -0.67350445, -0.26111648],
       [ 1.14519667, -0.5527708 , -1.08130975, ..., -0.26111648,
        -0.67350445, -0.26111648]])

In [13]:
from sklearn.svm import SVC

In [14]:
cls_svc = SVC(kernel='linear', random_state = 0)
cls_svc.fit(training_x,training_y)

SVC(kernel='linear', random_state=0)

In [15]:
y_pred = cls_svc.predict(testing_x)
y_pred # Prediction er value

array(['Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Catracts', 'Catracts', 'Oculer hypertension', 'Catracts',
       'Catracts', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Catracts', 'Catracts', 'Catracts',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Catracts', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Catracts', 'Catracts', 'Oculer hypertension', 'Catracts',
       'Oculer hypertension', 'Catracts', 

In [16]:
testing_y # real

array(['Congenital Glaucoma', 'Catracts', 'Oculer hypertension',
       'Congenital Glaucoma', 'Catracts', 'Catracts', 'Glaucoma ACG',
       'Catracts', 'Catracts', 'Glaucoma ACG', ' Bulgy Vision',
       'Catracts', 'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts',
       'Oculer hypertension', 'Oculer hypertension',
       'Oculer hypertension', 'Catracts', 'Oculer hypertension',
       'Catracts', 'Oculer hypertension', 'Congenital Glaucoma',
       'Catracts', 'Bulgy Vision', 'Oculer hypertension', 'Catracts',
       'Glaucoma ACG', 'Glaucoma ACG', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Oculer hypertension', 'Catracts',
       'Congenital Glaucoma', 'Congenital Glaucoma', 'Catracts',
       'Glaucoma ACG', 'Catracts', 'Catracts', 'Catracts', 'Catracts',
       'Congenital Glaucoma', 'Bulgy Vision', 'Catracts', 'Catracts',
       'C

# Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
confus_matrix = confusion_matrix(testing_y,y_pred)  # y_true = Real Value, y_pred = Prediction er value
confus_matrix

array([[ 0,  0,  4,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  2],
       [ 0,  0, 64,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  8],
       [ 0,  0,  8,  0,  3,  4],
       [ 0,  0,  0,  0,  0, 37]], dtype=int64)

# Accuracy

In [19]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(testing_y, y_pred))

Accuracy :  0.7375886524822695


In [21]:
print (accuracy_score(testing_y, y_pred)*100) # Accuracy

73.75886524822694


# precision, recall, f1-score, support


In [22]:
from sklearn.metrics import classification_report
print(classification_report(testing_y, y_pred))

                     precision    recall  f1-score   support

       Bulgy Vision       0.00      0.00      0.00         4
       Bulgy Vision       0.00      0.00      0.00         5
           Catracts       0.74      1.00      0.85        64
Congenital Glaucoma       0.00      0.00      0.00        16
       Glaucoma ACG       1.00      0.20      0.33        15
Oculer hypertension       0.73      1.00      0.84        37

           accuracy                           0.74       141
          macro avg       0.41      0.37      0.34       141
       weighted avg       0.63      0.74      0.64       141



C:\Users\Nayeem\.conda\envs\tensorflow 3_7\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
